---
# Tasks file for preparing the base OS for installation of Kali
# tools. This includes installation of Kali package signing keys,
# package dependencies, normalizing OS commands to match Kali
# distros, etc.

- name: Ensure Kali package pre-requisites are present.
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
      - apt-utils
      - dirmngr
      - gnupg
      - gnupg2
      - python3-lib2to3
      - python3-six
      - xz-utils
  become: true

- name: Ensure `gawk` is installed.
  ansible.builtin.apt:
    name: gawk
    state: present
    update_cache: false
  register: gawk_result
  become: true

- name: Work around some bug regarding `/usr/bin/awk`. # noqa no-handler
  ansible.builtin.command: update-alternatives --set awk /usr/bin/gawk
  become: true
  changed_when: false
  when: gawk_result.changed

- name: Prepare system for installing packages from Kali repos.
  include_tasks:
    file:  '{{ collection_root }}/tasks/enable_kali_packages.yml'

# vim: ft=ansible :
