---

# Tasks file for davedittrich.utils.kali_like role.

- name: Include account enumeration tasks.
  ansible.builtin.include_tasks: '{{ collection_root }}/tasks/get_accounts.yml'

- name: Set fact with relative local path.
  ansible.builtin.set_fact:
    kali_like__script_templates_dir: '{{ role_path }}/templates/scripts/'

- name: Include Kali base OS preparation tasks.
  ansible.builtin.include_tasks: prepare_for_kali_packages.yml

- name: Ensure required Kali packages are present.
  ansible.builtin.apt:
    name: "{{ kali_like__packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  changed_when: false
  become: true

- name: Hush Kali developer login message.
  ansible.builtin.command: 'touch ~/.hushlogin'
  loop: '{{ accounts }}'
  loop_control:
    loop_var: kali_like__user
  become: true
  become_user: '{{ kali_like__user }}'
  changed_when: false

- name: Find script templates on control host.
  ansible.builtin.find:
    paths: '{{ kali_like__script_templates_dir }}'
    recurse: false
    use_regex: false
    patterns: '*.sh.j2'
  delegate_to: localhost
  become: false
  register: kali_like__script_templates_matched

- name: Set fact with relative template paths.
  ansible.builtin.set_fact:
    kali_like__script_templates: '{{ kali_like__script_templates | default([]) + [item.path | basename] }}'
  loop: '{{ kali_like__script_templates_matched.files }}'

- name: Debug `kali_like__script_templates`.
  ansible.builtin.debug:
    var: kali_like__script_templates
    verbosity: 1
  changed_when: false

- name: Include helper script user installation tasks.
  ansible.builtin.include_tasks: install_helper_scripts.yml
  loop: '{{ accounts }}'
  loop_control:
    loop_var: user

# - name: Ensure Kali desktop-directories files exist
# TODO(dittrich): Complete this.

- name: Ensure applications-merged directory exists
  ansible.builtin.file:
    dest: '/etc/xdg/menus/applications-merged'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0o755
  become: true

- name: Ensure kali-applications.menu exists.
  ansible.builtin.copy:
    src: 'kali-applications.menu'
    dest: '/etc/xdg/menus/applications-merged/kali-applications.menu'
    owner: 'root'
    group: 'root'
    mode: 0o644
  become: true

- name: Include hostname configuration tasks.
  ansible.builtin.include_tasks: serial_hostname.yml

  # - name: Ensure kali icons are present
  # TODO(dittrich): Complete this.

- name: Include Guacamole installation tasks.
  ansible.builtin.include_tasks: '{{ collection_root }}/tasks/install_guacamole.yml'
  when: false

# vim: ft=ansible :
