---
# Prepare a Debian 11 (bullseye) system to include Kali Linux packages as well.
# This includes pre-requisite packages necessary for installation of
# Kali tools, Kali package signing keys, setting package priority
# policy, etc.
#
# See: https://www.kali.org/blog/advanced-package-management-in-kali-linux/

- name: Ensure Kali package pre-requisites are present.
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
      - apt-utils
      - dirmngr
      - gnupg
      - gnupg2
      - python3-lib2to3
      - python3-six
      - xz-utils
  become: true

- name: Ensure Debian sources in `/etc/apt/sources.list.d/debian.list`
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/debian.list
    content: |
      deb http://ftp.debian.org/debian unstable main contrib non-free
      deb http://deb.debian.org/debian experimental main
    owner: root
    group: root
    mode: 0o644
  become: true

- name: Ensure custom APT package priority policy is set.
  ansible.builtin.copy:
    dest: '/etc/apt/preferences.d/99-custom-policy'
    content: |
      # Priority of local package files is 100.
      # Default priority of packages is 500.
      # View policy with `apt-cache policy`.

      Package: *
      Pin: release a=kali-rolling
      Pin-Priority: 900

      Package: *
      Pin: release a=kali-bleeding-edge
      Pin-Priority: 800

      Package: *
      Pin: release a=unstable
      Pin-Priority: 600
    owner: 'root'
    group: 'root'
    mode: 0o644
  become: true

- name: Prepare system for installing packages from Kali repos.
  include_tasks:
    file:  '{{ collection_root }}/tasks/enable_kali_packages.yml'

- name: Ensure default distribution is `kali-rolling`.
  ansible.builtin.copy:
    dest: '/etc/apt/apt.conf.d/local'
    content: |
      DPkg::options { "--force-confdef"; "--force-confold"; }
      APT::Default-Release "kali-rolling";
    owner: 'root'
    group: 'root'
    mode: 0o644
  become: true

- name: Get current APT policy.
  ansible.builtin.shell: |
    set -x
    apt-cache policy
    apt-cache policy perl-base libcrypt1 libc6 dpkg
  changed_when: false
  register: apt_policy
  become: true

- name: Debug `apt_policy`.
  ansible.builtin.debug:
    var: apt_policy
    verbosity: 0

- name: Perform `dist-upgrade`.
  include_tasks: '{{ collection_root }}/tasks/dist-upgrade.yml'

# vim: ft=ansible :
