---

# Tasks file for setting hostname via serial number.

- name: Block to obtain serial number.
  block:

    - name: Ensure `dmidecode` is available.
      ansible.builtin.package:
        name: dmidecode
        state: present
      become: true

    - name: Retrieve serial number from `dmidecode`.
      ansible.builtin.shell:
        dmidecode -s system-serial-number
      args:
        executable: /bin/bash
      register: dmidecode
      changed_when: false
      failed_when: dmidecode is failed or dmidecode.stdout == "None"

    - name: Set fact with serial number.
      ansible.builtin.set_fact:
        system_serial_number: '{{ dmidecode.stdout }}'

  rescue:
    - name: Stat `/sys/class/dmi/id/board_serial` file.
      ansible.builtin.stat:
        path: '/sys/class/dmi/id/board_serial'
      register: result

    - name: Get serial number for host.
      ansible.builtin.shell: |
        echo -n $(cut -d/ -f 2 /sys/class/dmi/id/board_serial)
      changed_when: false
      register: board_serial

    - name: Set fact with serial number.
      ansible.builtin.set_fact:
        system_serial_number: '{{ board_serial.stdout }}'
      when:
        - result is success
        - result.stdout is defined
        - result.stdout != ""

- name: Set fact with host name based on serial number.
  ansible.builtin.set_fact:
    host_serial: 'kali-{{ system_serial_number }}'
  when:
    - system_serial_number is defined
    - system_serial_number != ""

- name: Set fact with generic host name.
  ansible.builtin.set_fact:
    host_serial: 'kali-generic'
  when: host_serial is not defined

- name: Debug `host_serial`
  ansible.builtin.debug:
    var: host_serial
    verbosity: 1

# TODO(dittrich): Add name to `/etc/hosts` file.

- name: Ensure hostname has serialized Kali host name.
  ansible.builtin.shell:
    hostname && hostname '{{ host_serial }}'
  args:
    executable: /bin/bash
  register: hostname
  changed_when: hostname is success and hostname.stdout != host_serial
  become: true

# vim: ft=ansible:
