---
- name: Converge
  hosts: all
  vars:
    collection_root: '{{ lookup("env", "COLLECTION_ROOT") }}'

  pre_tasks:
    - name: Update package cache.
      ansible.builtin.package:
        update_cache: true
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2

  roles:
    - davedittrich.utils.branding

  post_tasks:
    - name: Dump all variables used to converge for later use.  # noqa
      ansible.builtin.copy:
        content: |
          {{ vars | to_yaml }}
        dest: '{{ molecule_ephemeral_directory }}/ansible-vars.yml'
        mode: 0o600
      changed_when: false
      delegate_to: localhost

# vim: ft=ansible:
