---

# Configure natural scrolling for mouse and trackpad.

- name: Ensure user .Xmodmap files customize natural scrolling.
  ansible.builtin.include_tasks: user_xmodmap_natural_scrolling.yml
  vars:
    user: '{{ item }}'
  loop: '{{ accounts }}'

# vim: ft=ansible:
