---

# Configure left CapsLock and CTRL keys.

- name: Set fact `custom_udev_hwdb`.
  ansible.builtin.set_fact:
    kdmt__custom_udev_hwdb: '/etc/udev/hwdb.d/99-swapcapslockctrl.hwdb'
  when: kdmt__custom_udev_hwdb is not defined

- name: Determine state of `systemd-udevd`.
  ansible.builtin.shell: >
    systemctl is-active systemd-udevd
  args:
    executable: /bin/bash
  register: kdmt__udevd
  changed_when: false
  become: true

- name: Block for swapping left CapsLock and CTRL keys.
  when: keyboard_swapcapslockctrl | bool
  become: true
  block:

    - name: 'Ensure file exists: {{ kdmt__custom_udev_hwdb }}'
      ansible.builtin.copy:
        dest: '{{ kdmt__custom_udev_hwdb }}'
        content: |
          # Match all usb keyboards
          evdev:input:b0003v*p*
          # Remap CapsLock <-> Left CTRL
          KEYBOARD_KEY_70039=leftctrl
          KEYBOARD_KEY_700E0=capslock
        owner: root
        group: root
        mode: 0o644
      register: kdmt__udev_hwdb
      become: true

    - name: Debug ``udev_hwdb``.
      ansible.builtin.debug:
        msg: '{{ kdmt__udev_hwdb }}'
        verbosity: 2

    - name: Update udevadm hwdb and trigger update.
      ansible.builtin.shell: >
        udevadm hwdb --update && udevadm trigger
      args:
        executable: /bin/bash
      register: kdmt__trigger
      until: kdmt__trigger is success
      retries: 1
      delay: 30
      when: "udevd.stdout == 'active' and kdmt__udev_hwdb.changed"
      changed_when: kdmt__trigger is success
      become: true

    - name: Ensure `ctrl:swapcaps` in `/etc/default/keyboard`.
      ansible.builtin.lineinfile:
        path: '/etc/default/keyboard'
        regexp: '^XKBOPTIONS=""'
        line: 'XKBOPTIONS="ctrl:swapcaps"'
        state: present
      become: true

    - name: Ensure keyboard is reconfigured.
      ansible.builtin.shell: |
        dpkg-reconfigure keyboard-configuration && debconf-show keyboard-configuration
      args:
        executable: /bin/bash
      environment:
        DEBIAN_FRONTEND: "noninteractive"
      register: kdmt__result
      changed_when: false
      failed_when:
        - kdmt__result.rc != 0
        - "'ctrl:swapcaps' not in kdmt__result.stdout"
      become: true

- name: Block for restoring normal CapsLock and CTRL keys.
  when: not keyboard_swapcapslockctrl | bool
  become: true
  block:

    - name: 'Ensure file is absent: {{ kdmt__custom_udev_hwdb }}'
      ansible.builtin.file:
        path: '{{ kdmt__custom_xmodmap }}'
        state: absent
      register: kdmt__udev_hwdb

    - name: Update udevadm hwdb and trigger update.
      ansible.builtin.shell: >
        udevadm hwdb --update && udevadm trigger
      args:
        executable: /bin/bash
      register: kdmt__trigger
      until: kdmt__trigger is success
      retries: 1
      delay: 30
      when: "udevd.stdout == 'active' and kdmt__udev_hwdb.changed"
      changed_when: kdmt__trigger is success
      become: true

- name: Include user .Xmodmap file customization tasks.
  ansible.builtin.include_tasks: user_xmodmap_capslockctrl.yml
  vars:
    kdmt__user: '{{ item }}'
  loop: '{{ accounts }}'

# vim: ft=ansible:
