---

# Quiet keyboard bell sounds for lab systems.

- name: Ensure user init files are configured for visible bell.
  ansible.builtin.include_tasks: user_visible_bell.yml
  vars:
    user: '{{ item }}'
  loop: '{{ accounts }}'

# vim: ft=ansible:
