---

# Configure natural scrolling for mouse and trackpad.

- name: Include user .Xmodmap natural scrolling tasks.
  ansible.builtin.include_tasks: user_xmodmap_natural_scrolling.yml
  vars:
    kdmt__user: '{{ item }}'
  loop: '{{ accounts }}'

# vim: ft=ansible:
