---

# Quiet keyboard bell sounds for lab systems.

- name: Include user visible bell init file configuration.
  ansible.builtin.include_tasks: user_visible_bell.yml
  vars:
    kdmt__user: '{{ item }}'
  loop: '{{ accounts }}'

# vim: ft=ansible:
