---

# Configure left CapsLock and CTRL keys.

- name: Set fact `custom_xmodmap`.
  ansible.builtin.set_fact:
    custom_xmodmap: '/etc/X11/Xsession.d/40custom_load_xmodmap'
  when: custom_xmodmap is not defined

- name: Set fact `custom_udev_hwdb`.
  ansible.builtin.set_fact:
    custom_udev_hwdb: '/etc/udev/hwdb.d/99-swapcapslockctrl.hwdb'
  when: custom_udev_hwdb is not defined

- name: Stat `/etc/X11/Xsession.d` directory.
  ansible.builtin.stat:
    path: /etc/X11/Xsession.d
  register: xsessiond

- name: Determine state of `systemd-udevd`.
  ansible.builtin.shell: >
    systemctl is-active systemd-udevd
  args:
    executable: /bin/bash
  register: udevd
  changed_when: false
  become: true

- name: Block for swapping left CapsLock and CTRL keys.
  when: keyboard_swapcapslockctrl is true
  become: true
  block:

    - name: Ensure `{{ custom_xmodmap }}` dropin exists.
      ansible.builtin.copy:
        dest: '{{ custom_xmodmap }}'
        content: |
          SYSMODMAP="/etc/X11/Xmodmap"
          USERMODMAP="$HOME/.Xmodmap"
          XMODMAP="/usr/bin/xmodmap"

          if [ -x "$XMODMAP" ]; then
              for map in "$SYSMODMAP" "$USERMODMAP"; do
                  if [ -f "$map" ]; then
                      logger "running $XMODMAP $map"
                      $XMODMAP "$map"
                  fi
              done
          fi
        owner: root
        group: root
        mode: 0o644
      when: xsessiond.stat.exists

    - name: Ensure `{{ custom_udev_hwdb }}` file exists.
      ansible.builtin.copy:
        dest: '{{ custom_udev_hwdb }}'
        content: |
          # Match all usb keyboards
          evdev:input:b0003v*p*
          # Remap CapsLock <-> Left CTRL
          KEYBOARD_KEY_70039=leftctrl
          KEYBOARD_KEY_700E0=capslock
        owner: root
        group: root
        mode: 0o644
      register: udev_hwdb
      become: true

    - name: Debug ``udev_hwdb``.
      ansible.builtin.debug:
        msg: '{{ udev_hwdb }}'
        verbosity: 2

    - name: Update udevadm hwdb and trigger update.
      ansible.builtin.shell: >
        udevadm hwdb --update && udevadm trigger
      args:
        executable: /bin/bash
      register: trigger
      until: trigger is success
      retries: 1
      delay: 30
      when: "udevd.stdout == 'active' and udev_hwdb.changed"
      become: true

    - name: Ensure `ctrl:swapcaps` in `/etc/default/keyboard`.
      ansible.builtin.lineinfile:
        path: '/etc/default/keyboard'
        regexp: '^XKBOPTIONS=""'
        line: 'XKBOPTIONS="ctrl:swapcaps"'
        state: present
      become: true

    - name: Ensure keyboard is reconfigured.
      ansible.builtin.shell: |
        dpkg-reconfigure keyboard-configuration && debconf-show keyboard-configuration
      args:
        executable: /bin/bash
      environment:
        DEBIAN_FRONTEND: "noninteractive"
      register: result
      changed_when: false
      failed_when:
        - result.rc != 0
        - "'ctrl:swapcaps' not in result.stdout"
      become: true

- name: Block for restoring normal CapsLock and CTRL keys.
  when: keyboard_swapcapslockctrl is false
  become: true
  block:

    - name: Ensure `{{ custom_xmodmap }}` is absent.
      ansible.builtin.file:
        path: '{{ custom_xmodmap }}'
        state: absent
      register: xmodmap

    - name: Ensure `{{ custom_udev_hwdb }}` is absent.
      ansible.builtin.file:
        path: '{{ custom_xmodmap }}'
        state: absent
      register: udev_hwdb

    - name: Update udevadm hwdb and trigger update.
      ansible.builtin.shell: >
        udevadm hwdb --update && udevadm trigger
      args:
        executable: /bin/bash
      register: trigger
      until: trigger is success
      retries: 1
      delay: 30
      when: "udevd.stdout == 'active' and udev_hwdb.changed"
      become: true

- name: Ensure user Xmodmap files are customized.
  ansible.builtin.include_tasks: user_xmodmap.yml
  vars:
    user: '{{ item }}'
  loop: '{{ accounts }}'
  when: xsessiond.stat.exists


# vim: ft=ansible:
