---

# Tasks file for davedittrich.utils.kdmt
# This roles is for configuring custom keyboard, display, mouse,
# and trackpad settings.

- name: Set fact with users whose accounts need to be configured
  ansible.builtin.set_fact:
    accounts: '{{ accounts | default(["root", ansible_user_id]) | unique }}'

- name: Ensure user home directories are mapped.
  include_tasks: '{{ collection_root }}/tasks/get_homedir.yml'
  loop: '{{ accounts }}'
  loop_control:
    loop_var: user

- name: Ensure required packages are present.
  ansible.builtin.package:
    name:
      - keyboard-configuration
      - console-setup
      - udev
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

  # K is for keyboard.

- name: Include keyboard function keys configuration tasks.
  ansible.builtin.include_tasks: configure_keyboard_hid_apple.yml

- name: Include capslockctrl configuration tasks.
  ansible.builtin.include_tasks: configure_keyboard_capslockctrl.yml

- name: Include visible bell configuration tasks.
  ansible.builtin.include_tasks: configure_keyboard_visible_bell.yml
  vars:
    user: "{{ item }}"
  loop: '{{ accounts }}'

  # D is for display.

  # M is for mouse.

  # - name: Include mouse configuration tasks.
  #   ansible.builtin.include_tasks: configure_mouse.yml
  #   when: natural_scrolling is true

  # T is for trackpad.

  # - name: Include trackpad configuration tasks.
  #   ansible.builtin.include_tasks: configure_trackpad.yml
  #   when: natural_scrolling is true

# EOF
