---

# Configure Xsession.d dropin for custom user Xmodmap files.

- name: Stat `/etc/X11/Xsession.d` directory.
  ansible.builtin.stat:
    path: /etc/X11/Xsession.d
  register: xsessiond

- name: Set fact `custom_xmodmap`.
  ansible.builtin.set_fact:
    custom_xmodmap: '/etc/X11/Xsession.d/40custom_load_xmodmap'
  when: custom_xmodmap is not defined

- name: 'Ensure dropin exists: {{ custom_xmodmap }}'
  ansible.builtin.copy:
    src: 'custom_load_xmodmap'
    dest: '{{ custom_xmodmap }}'
    owner: root
    group: root
    mode: 0o644
  when: xsessiond.stat.exists

# vim: ft=ansible:
