---

# Customize user .Xmodmap file for capslock/ctrl keys.

- name: 'Block for customizing file: {{ kdmt__user_xmodmap[kdmt__user] }}'
  become: true
  become_user: '{{ kdmt__user }}'
  block:

    - name: 'Ensure file swaps capslock/ctrl: {{ kdmt__user_xmodmap[kdmt__user] }}'
      ansible.builtin.blockinfile:
        path: '{{ kdmt__user_xmodmap[kdmt__user] }}'
        marker: '# {mark} ANSIBLE MANAGED BLOCK [davedittrich.utils.kdmt:capslockctrl]'
        block: |
          !
          ! Swap Caps_Lock and Control_L
          !
          remove Lock = Caps_Lock
          remove Control = Control_L
          keysym Control_L = Caps_Lock
          keysym Caps_Lock = Control_L
          add Lock = Caps_Lock
          add Control = Control_L
        create: true
        owner: '{{ kdmt__user }}'
        group: '{{ kdmt__user }}'
        mode: 0o640
      when: kdmt__keyboard_swapcapslockctrl | bool

    - name: 'Ensure file does not swap capslock/ctrl: {{ kdmt__user_xmodmap[kdmt__user] }}'
      ansible.builtin.blockinfile:
        path: '{{ kdmt__user_xmodmap[kdmt__user] }}'
        marker: '# {mark} ANSIBLE MANAGED BLOCK [davedittrich.utils.kdmt:capslockctrl]'
        block: ''
        create: true
        owner: '{{ kdmt__user }}'
        group: '{{ kdmt__user }}'
        mode: 0o640
      when: not kdmt__keyboard_swapcapslockctrl | bool

# vim: ft=ansible:
