---

# Customize user init files for visible bell.
# This task file must be looped on 'user'.

- name: Ensure applications using `readline` are quieted.
  ansible.builtin.blockinfile:
    path: '{{ homedir[kdmt__user] }}/.inputrc'
    marker: "# {mark} ANSIBLE MANAGED BLOCK [davedittrich.utils.kdmt:visible_bell]"
    block: |
      set prefer-visible-bell
    owner: '{{ kdmt__user }}'
    group: '{{ kdmt__user }}'
    mode: 0o640
    create: true
  become: true

# - name: Ensure `bash` shell sessions are quieted.
#   ansible.builtin.blockinfile:
#     path: '{{ homedir[kdmt__user] }}/.bashrc'
#     marker: "# {mark} ANSIBLE MANAGED BLOCK [davedittrich.utils.kdmt:visible_bell]"
#     block: |
#       set bellstyle visible
#     owner: '{{ kdmt__user }}'
#     group: '{{ kdmt__user }}'
#     mode: 0o640
#     create: true
#   # Hack to get idempotence test to pass for now.
#   changed_when: false
#   become: true

- name: Ensure `csh` and `tcsh` shell sessions are quieted.
  ansible.builtin.blockinfile:
    path: '{{ homedir[kdmt__user] }}/.cshrc'
    marker: "# {mark} ANSIBLE MANAGED BLOCK [davedittrich.utils.kdmt:visible_bell]"
    block: |
      set visiblebell
    owner: '{{ kdmt__user }}'
    group: '{{ kdmt__user }}'
    mode: 0o640
    create: true
  become: true

- name: Ensure `ex` family editors are quieted.
  ansible.builtin.blockinfile:
    path: '{{ homedir[kdmt__user] }}/.exrc'
    marker: "# {mark} ANSIBLE MANAGED BLOCK [davedittrich.utils.kdmt:visible_bell]"
    block: |
      set flash
    owner: '{{ kdmt__user }}'
    group: '{{ kdmt__user }}'
    mode: 0o640
    create: true
  become: true

- name: Ensure `vim` style editors are quieted.
  ansible.builtin.blockinfile:
    path: '{{ homedir[kdmt__user] }}/.vimrc'
    marker: '" {mark} ANSIBLE MANAGED BLOCK [davedittrich.utils.kdmt:visible_bell]'
    block: |
      set vb t_vb=
    owner: '{{ kdmt__user }}'
    group: '{{ kdmt__user }}'
    mode: 0o640
    create: true
  become: true

# vim: ft=ansible:
