---

# Perform a `dist-upgrade`. Doing this may result in a major update
# to Python, which can break `pipx` and programs installed with it.
# After the upgrade, check all accounts on the system that have
# a `~/.local/pipx` directory and repair them.

- name: Block to ensure packages upgraded.
  block:
    - name: Ensure `dist-upgrade` performed.
      ansible.builtin.apt:
        update_cache: false
        install_recommends: true
        force_apt_get: true
        upgrade: dist
      register: dist_upgrade
      become: true

  rescue:
    - name: Include broken dist-upgrade repair tasks.
      ansible.builtin.include_tasks: '{{ collection_root }}/tasks/fix_broken_install.yml'

- name: Include broken user `pipx` repair tasks.
  ansible.builtin.include_tasks: '{{ collection_root }}/tasks/check_repair_user_pipx.yml'
  loop: '{{ homedir.keys() }}'
  loop_control:
    loop_var: user

# vim: ft=ansible :
