---

# Pass in user as `user`.
# Use in playbooks as follows:
#
# - name: Ensure user home directories are mapped.
#   include_task:
#     file: ../../../tasks/get_homedir.yml
#   loop: '{{ users }}'
#   loop_control:
#     loop_var: user
#
# ...
#   path: "{{ homedir[user] ~ '/.filename' }}"
# ...

- name: Ensure `homedir` dictionary exists.
  ansible.builtin.set_fact:
    homedir: {}
  when: homedir is not defined

- name: Block
  block:

    - name: Get user home directory with `getent`.
      ansible.builtin.shell: |
        set -o pipefail
        getent passwd {{ user }} | awk -F: '{ print $6 }'
      args:
        executable: /bin/bash
      changed_when: false
      register: getent

    - name: Append to `homedir` dictionary.
      ansible.builtin.set_fact:
        homedir: "{{ homedir | combine({ user: getent.stdout }) }}"

    - name: Debug `homedir`.
      ansible.builtin.debug:
        var: homedir

  when: user not in homedir
