---
- name: Converge
  hosts: all
  vars:
    collection_root: '{{ lookup("env", "COLLECTION_ROOT") }}'

  roles:
    - davedittrich.utils.dropins

  post_tasks:
    - name: Dump all variables used to converge for later use.  # noqa
      ansible.builtin.copy:
        content: |
          {{ vars | to_yaml }}
        dest: '{{ molecule_ephemeral_directory }}/ansible-vars.yml'
        mode: 0o600
      changed_when: false
      delegate_to: localhost

# vim: ft=ansible:
