all:
  vars:
    ansible_python_interpreter: '{{ lookup("pipe", "type python3").split()[2] }}'
    ansible_user_id: '{{ lookup("env", "USER") }}'
    ansible_connection: local
  hosts:
    localhost:
