galaxy_info:
  author: Dave Dittrich
  description: Ansible role to add specific Kali packages to make a "Kali-like" system.
  # issue_tracker_url: http://example.com/issue/tracker
  license: Apache-2.0
  min_ansible_version: 2.1
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: RedHat
      versions:
        - all
  galaxy_tags:
    - collection
    - role
dependencies: []
