---
# tasks file for davedittrich.utils.visible_bell

# This role implements settings described in the following page:
# https://tldp.org/HOWTO/Visual-Bell-8.html

- name: Ensure package cache is up to date.
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Set fact with users whose accounts need to be configured.
  ansible.builtin.set_fact:
    accounts: "{{ accounts | default(['root', ansible_user_id]) | unique }}"

- name: Debug `accounts`.
  ansible.builtin.debug:
    msg: '{{ accounts }}'
    verbosity: 2

- name: Get user home directories.
  include_tasks: '{{ collection_root }}/tasks/get_homedir.yml'
  loop: '{{ accounts }}'
  loop_control:
    loop_var: user

- name: Ensure quieting applied to intended users.
  include_tasks:
    file: visible_bell.yml
  vars:
    user: "{{ item }}"
  loop: '{{ accounts }}'
