---
# tasks file for davedittrich.utils.visible_bell

# This role implements settings described in the following page:
# https://tldp.org/HOWTO/Visual-Bell-8.html

- name: Ensure package cache is up to date.
  ansible.builtin.package:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Set fact with users whose accounts need to be configured
  ansible.builtin.set_fact:
    visible_bell_users: "{{ visible_bell_users | default(['root', ansible_user_id]) | unique }}"

- name: Debug `visible_bell_users`.
  ansible.builtin.debug:
    msg: '{{ visible_bell_users }}'
    verbosity: 2

- name: Ensure quieting applied to intended users.
  include_tasks: visible_bell.yml
  vars:
    user: "{{ item }}"
  loop: '{{ visible_bell_users }}'
