---

- name: Get user home directory with `getent`.
  ansible.builtin.shell: |
    set -o pipefail
    getent passwd {{ user }} | awk -F: '{ print $6 }'
  args:
    executable: /bin/bash
  changed_when: false
  register: getent

- name: Set fact with user home directory
  ansible.builtin.set_fact:
    homedir: "{{ getent.stdout }}"

- name: Debug `homedir`.
  ansible.builtin.debug:
    var: homedir

- name: Ensure applications using `readline` are quieted.
  ansible.builtin.blockinfile:
    path: "{{ homedir ~ '/.inputrc' }}"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0o640
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      set prefer-visible-bell
    create: true
  become: true

- name: Ensure `bash` shell sessions are quieted.
  ansible.builtin.blockinfile:
    path: "{{ homedir ~ '/.bashrc' }}"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0o640
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      set bellstyle visible
    create: true
  become: true

- name: Ensure `csh` and `tcsh` shell sessions are quieted.
  ansible.builtin.blockinfile:
    path: "{{ homedir ~ '/.cshrc' }}"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0o640
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      set visiblebell
    create: true
  become: true

- name: Ensure `ex` family editors are quieted.
  ansible.builtin.blockinfile:
    path: "{{ homedir ~ '/.exrc' }}"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0o640
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    block: |
      set flash
    create: true
  become: true

- name: Ensure `vim` style editors are quieted.
  ansible.builtin.blockinfile:
    path: "{{ homedir ~ '/.vimrc' }}"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0o640
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    block: |
      set vb t_vb=
    create: true
  become: true
