---
role_name_check: 2
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  make version
  make dependencies
  yamllint molecule/ playbooks/ plugins/ roles/ tasks/
  flake8 molecule/shared/tests playbooks/ plugins/ roles/ tasks/
  ansible-lint -vvv -c .ansible-lint molecule/shared/tests playbooks/ plugins/ tasks/
platforms:
  - name: instance
    image: "davedittrich/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-"/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns: host
    privileged: true
    pre_build_image: true
    pull: false
# [molecule.yml-provisioner]
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_VERBOSITY: ${ANSIBLE_VERBOSITY:-1}
    COLLECTION_ROOT: "${PWD}"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
  inventory:
    hosts:
      all:
        vars:
          accounts:
            - 'root'
          mysql_password: '_molecule_mysql_password'
          guacamole_password: '_molecule_guacamole_password'
# ![molecule.yml-provisioner]
scenario:
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - create
    - prepare
    - converge
    - idempotence
    - verify
verifier:
  name: testinfra
  directory: ../shared/tests
  options:
    # Add a -v so you see the individual test names.
    vv: true
    pdb: true
  additional_files_or_dirs:
    - ../shared/*
