---

# Tasks file for davedittrich.utils.dropins role.

- name: Ensure `accounts` and home directory map are defined.
  ansible.builtin.include_tasks: '{{ collection_root }}/tasks/get_accounts.yml'

- name: Ensure `dropins__dropin_files` has dropin directories to create.
  ansible.builtin.set_fact:
    dropins__dropin_files: '{{ dropins__default_dropin_files }}'
  when: dropins__dropin_files is not defined

- name: Debug `dropins__dropin_files` variable.
  ansible.builtin.debug:
    var: dropins__dropin_files
    verbosity: 0

- name: Include `pipx` user account repair tasks.
  ansible.builtin.include_tasks: '{{ collection_root }}/tasks/check_repair_user_pipx.yml'
  loop: '{{ accounts }}'
  loop_control:
    loop_var: user

- name: Include `update-dotdee` user installation tasks.
  ansible.builtin.include_tasks: setup_update_dotdee.yml
  loop: '{{ accounts }}'
  loop_control:
    loop_var: user

# https://stackoverflow.com/questions/58110659/issue-passing-variable-to-include-task-file-having-add-host-in-ansible

- name: Include dropin directory setup tasks.
  ansible.builtin.include_tasks: setup_dropin.yml
  vars:
    user: '{{ item.0 }}'
    dropins__dropin_file: '{{ item.1 }}'
  with_nested:
    - '{{ accounts }}'
    - '{{ dropins__dropin_files }}'

- name: Ensure `PATH` contains users' `.local/bin` directories.
  ansible.builtin.copy:
    src: dotlocal.sh
    dest: /etc/profile.d/dotlocal.sh
    owner: root
    group: root
    mode: 0o644
  become: true

# vim: ft=ansible :
