---

# Ensure that `update-dotdee` is installed using `pipx` to be
# a self-contained virtualenv application.
#
# Pass in user account name as `user`.

# Since you can't `become` and `become_user` with `include_tasks`, do it
# here on the `block` instead to be more DRY in plays.

- name: Block
  become: true
  block:

    - name: Ensure `updated-dotdee` installed with `pipx`.
      ansible.builtin.shell: |
        type update-dotdee || pipx install update-dotdee
      args:
        creates:
          - '{{ homedir[user] }}/.local/bin/update-dotdee'
        executable: /bin/bash
      environment:
        PATH: '{{ homedir[user] }}/.local/bin:{{ ansible_env.PATH }}'
      become_user: '{{ user }}'
      register: result
      # failed_when: "result.rc != 0 'already seems to be installed' not in result.stdout"
      changed_when: "'update-dotdee is' not in result.stdout"

# vim: ft=ansible :
