FROM debian:bullseye
LABEL maintainer="Dave Dittrich"

ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y \
      aptitude \
      arandr \
      bash \
      build-essential \
      ca-certificates \
      fbi \
      hwinfo \
      imagemagick \
      iproute2 \
      libffi-dev \
      libssl-dev \
      procps \
      python3 \
      python3-apt \
      python3-dev \
      python3-pip \
      python3-setuptools \
      python3-wheel \
      python3-venv \
      rsync \
      sudo \
      systemd \
      systemd-sysv \
      task-lxde-desktop \
      wget \
      vim \
      tree \
    && pip3 install --upgrade pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
    /lib/systemd/system/systemd-update-utmp*

EXPOSE 80/tcp
EXPOSE 443/tcp

RUN systemctl enable systemd-networkd
RUN systemctl set-default multi-user.target

#VOLUME [ "/sys/fs/cgroup" ]

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]
