---
# Ensure files to be modified exist.

- name: Prepare instance.  # noqa: parse-error
  hosts: all
  gather_facts: false
  vars:
    collection_root: '{{ lookup("env", "COLLECTION_ROOT") }}'

  tasks:
    - name: Stat `/boot/config.txt` file.
      ansible.builtin.stat:
        path: '/boot/config.txt'
      register: boot_config

    - name: Ensure `/boot/config.txt` file exists in instance.
      ansible.builtin.copy:
        src: 'config.txt'
        dest: '/boot/config.txt'
        owner: 'root'
        group: 'root'
        mode: '0o640'
      when: boot_config.stat.exists is false

    - name: Stat `/boot/cmdline.txt` file.
      ansible.builtin.stat:
        path: '/boot/cmdline.txt'
      register: boot_cmdline

    - name: Ensure `/boot/cmdline.txt` file exists in instance.
      ansible.builtin.copy:
        src: 'cmdline.txt'
        dest: '/boot/cmdline.txt'
        owner: 'root'
        group: 'root'
        mode: '0o640'
      when: boot_cmdline.stat.exists is false

    - name: Include account enumeration tasks.
      ansible.builtin.include_tasks: '{{ collection_root }}/tasks/get_accounts.yml'

    - name: Ensure SSH directory exists for `davedittrich.utils.dropin` role.
      ansible.builtin.file:
        path: '{{ homedir[user] }}/.ssh'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0o700'
      loop: '{{ accounts }}'
      loop_control:
        loop_var: user
      become: true

# vim: ft=ansible:
