---
dependency:
  name: galaxy
# [delegated-molecule.yml-driver]
# See: https://github.com/ansible-community/molecule/issues/1518
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: 'ssh {instance} -F delegated-ssh-config'
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: -F delegated-ssh-config
platforms:
  - name: delegated-host
# ![delegated-molecule.yml-driver]
lint: |
  make version
  make dependencies
  yamllint molecule/ playbooks/ plugins/ roles/ tasks/
  flake8 molecule/shared/tests playbooks/ plugins/ roles/ tasks/
  ansible-lint -vvv -c .ansible-lint molecule/shared/tests playbooks/ plugins/ roles/ tasks/
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: ${ANSIBLE_FORCE_COLOR:-true}
    ANSIBLE_VERBOSITY: ${ANSIBLE_VERBOSITY:-0}
    COLLECTION_ROOT: "${PWD}"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
  inventory:
    hosts:
      all:
        vars:
          accounts:
            - 'root'
            - 'pirate'
verifier:
  name: testinfra
  directory: ../shared/tests
  env:
    PYTHONPATH: "${PWD}/molecule/shared/tests"
    #PYTEST_ADDOPTS: "--debug -v -ra --trace-config"
    PYTEST_ADDOPTS: "${PYTEST_ADDOPTS:--v -ra}"
  options:
    # The following is necessary to cause `molecule` to run `testinfra` with
    # elevated permissions using `ssh` to access the remote delegated host.
    # Failing to do this results in tests requiring `root` read and/or
    # execute access to directories and files to fail (and thus those tests
    # will also fail.)
    # See: https://github.com/ansible-community/molecule/issues/555
    sudo: true
