---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  destroy_sequence:
    - dependency
    - destroy
  test_sequence:
    - dependency
    - lint
    - create
    - prepare
    - converge
    - idempotence
    - verify
  verify_sequence:
    - verify
lint: |
  make version
  make dependencies
  yamllint molecule/ playbooks/ plugins/ roles/ tasks/
  flake8 molecule/shared/tests playbooks/ plugins/ roles/ tasks/
  ansible-lint -vvv -c .ansible-lint molecule/shared/tests playbooks/ plugins/ tasks/
platforms:
  - name: debian_bullseye
    image: debian:bullseye
    dockerfile: ../shared/Dockerfile-debian_bullseye.j2
    privileged: true
    override_command: false
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_VERBOSITY: ${ANSIBLE_VERBOSITY:-1}
    COLLECTION_ROOT: "${PWD}"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
verifier:
  name: testinfra
  directory: ../shared/tests
  options:
    # Add a -v so you see the individual test names.
    v: true
