---

# Ensure clipit history is disabled (to avoid the user being asked
# about this on first login session).

- name: Stat clipit configuration file.
  ansible.builtin.stat:
    path: '{{ homedir[branding__user] }}/.config/clipit/clipitrc'
  register: branding__clipitrc
  become: true

- name: Ensure clipit configuration path is present.
  ansible.builtin.file:
    dest: '{{ homedir[branding__user] }}/.config/clipit'
    state: directory
    owner: '{{ branding__user }}'
    group: '{{ branding__user }}'
    mode: 0o750
    recurse: false
  become: true

- name: Ensure clipit configuration is present.
  ansible.builtin.copy:
    src: 'clipitrc'
    dest: '{{ homedir[branding__user] }}/.config/clipit/clipitrc'
    owner: '{{ branding__user }}'
    group: '{{ branding__user }}'
    mode: 0o640
  become: true
  when: not branding__clipitrc.stat.exists

- name: Ensure clipit configuration is set.
  ansible.builtin.lineinfile:
    path: '{{ homedir[branding__user] }}/.config/clipit/clipitrc'
    regexp: '^save_history='
    line: 'save_history=false'
  become: true

# vim: ft=ansible:
