---

# tasks for configuring customized LXDE sessions.

- name: Set fact with LXDE package.
  ansible.builtin.set_fact:
    lxde_package: '{{ "task-lxde-desktop" if ansible_distribution == "Debian" else "lxde4" }}'

# Speed up molecule testing.
- name: Set fact with LXDE package install flag.
  ansible.builtin.set_fact:
    install_lxde: '{{ install_lxde | default(true) }}'

# HypriotOS switches the default Python from 2.x to 3.x. This breaks the old
# and not well-maintained 'wicd' service:
#
# Sep 15 23:34:20 hypriot systemd[1]: Starting Wicd a wireless and wired network manager for Linux...
# Sep 15 23:34:20 hypriot wicd[17037]:   File "/usr/share/wicd/daemon/wicd-daemon.py", line 136
# Sep 15 23:34:20 hypriot wicd[17037]:     print "--no-autoconnect detected, not autoconnecting..."
# Sep 15 23:34:20 hypriot wicd[17037]:                                                            ^
# Sep 15 23:34:20 hypriot wicd[17037]: SyntaxError: Missing parentheses in call to 'print'.
# Sep 15 23:34:20 hypriot wicd[17037]: Did you mean print("--no-autoconnect detected, not autoconnecting...")?
# Sep 15 23:34:20 hypriot systemd[1]: wicd.service: Main process exited, code=exited, status=1/FAILURE
# Sep 15 23:34:20 hypriot systemd[1]: wicd.service: Failed with result 'exit-code'.
# Sep 15 23:34:20 hypriot systemd[1]: Failed to start Wicd a wireless and wired network manager for Linux.
#
# The result is that adding any new packages (like we are about to do next) forces
# reconfiguration, which restarts services and the 'wicd.service' failure breaks
# the play. Deleting the packages causes other problems, so just stop and
# disable it now.

- name: Ensure `wicd.service` is masked.
  ansible.builtin.systemd:
    name: 'wicd'
    masked: true
  failed_when: false
  changed_when: false

- name: Ensure LXDE packages are present.
  ansible.builtin.apt:
    name:
      - 'arandr'
      - 'hwinfo'
      - '{{ lxde_package }}'
    state: present
    install_recommends: false
  become: true
  when: install_lxde

# https://linuxmeerkat.wordpress.com/2014/10/17/running-a-gui-application-in-a-docker-container/

- name: Ensure X11 settings are present in autostart file.
  include_tasks: x11-config.yml
  # vars:
  #   user: "{{ branding_user }}"
  loop: '{{ branding_users }}'
  loop_control:
    loop_var: user
