---

- name: Apply `davedittrich.utils.branding` role.
  hosts: all
  gather_facts: true
  vars:
    collection_root: "{{ lookup('env', 'COLLECTION_ROOT')|default(playbook_dir|dirname) }}"

  roles:
    - davedittrich.utils.branding

# vim: ft=ansible:
