---

- hosts: localhost
  gather_facts: false
  vars:
    source_images:
      - "geerlingguy/docker-debian10-ansible:latest"
      - "geerlingguy/docker-debian9-ansible:latest"
      - "geerlingguy/docker-ubuntu2004-ansible:latest"
      - "geerlingguy/docker-ubuntu1804-ansible:latest"
  tasks:
    - name: Ensure `repo_name` is defined.
      ansible.builtin.set_fact:
        repo_name: "{{ lookup('env', 'COLLECTION_NAMESPACE') }}"
      when: repo_name is not defined

    - name: Assert `repo_name` is not null.
      ansible.builtin.assert:
        that:
          - repo_name != ''
        fail_msg: "environment variable 'COLLECTION_NAMESPACE' not set"

    - name: Build custom molecule test image.
      include_tasks: ../tasks/build_one_image.yml
      loop: '{{ source_images }}'
      loop_control:
        loop_var: source_image
