---
- hosts: localhost
  gather_facts: false
  vars:
    keep_source_image: true
    packages:
  tasks:
    - name: Ensure `target_distros` is defined.
      ansible.builtin.set_fact:
        target_distros:
          - "debian11"
          - "debian10"
          - "ubuntu2204"
          - "ubuntu2004"
      when: target_distros is not defined

    - name: Ensure `repo_name` is defined.
      ansible.builtin.set_fact:
        repo_name: "{{ lookup('env', 'COLLECTION_NAMESPACE') }}"
      when: repo_name is not defined

    - name: Assert `repo_name` is not null.
      ansible.builtin.assert:
        that:
          - repo_name != ''
        fail_msg: "environment variable 'COLLECTION_NAMESPACE' not set"

    - name: Build custom molecule test image.
      include_tasks:
        file: ../tasks/build_one_image.yml
      loop: "{{ target_distros }}"
      loop_control:
        loop_var: target_distro
