---

- hosts: all
  gather_facts: true
  vars:
    collection_root: "{{ lookup('env', 'COLLECTION_ROOT')|default(playbook_dir|dirname) }}"

  roles:
    - role: davedittrich.utils.dropins
      vars:
        dropin_files:
          - '.bash_profile'
          - '.bash_aliases'
          - '.gitconfig'
          - '.ssh/config'
