---
- hosts: all
  gather_facts: true

  roles:
    - davedittrich.utils.dropins
      vars:
        users: '{{ users |default(['root', ansible_user_id]) | unique }}'
        dropin_files:
          - '.bash_profile'
          - '.bash_aliases'
          - '.gitconfig'
          - '.ssh/config'
