---
# Playbook to install zaproxy from a locally-downloaded DEB file.
#
# By design, Ansible does not use the current working directory
# and so installing the package from the current working directory
# when running the playbook from another directory requires
# you get around this by adding '-e cwd=$(pwd)' on the command line.
#

- name: Playbooks to install `zaproxy` from local DEB file.
  hosts: '{{ host | default("all") }}'
  gather_facts: false

  vars:
    zaproxy_version: '2.11.1-0kali1'
    zaproxy_sha256sum: '7da3e4a0307af87fbfeb92bc92b9dda3ee9b9c1c4309660b63d48618b012f35e'
    zaproxy_installed: false

  tasks:
    - name: Include check_reachable.yml task.
      ansible.builtin.include_tasks: '{{ collection_root }}/tasks/check_reachable.yml'

    - name: Set fact with package source directory.
      ansible.builtin.set_fact:
        zaproxy_deb_dir: '{{ zaproxy_deb_dir | default(cwd) }}/'

    - name: Set fact with zaproxy DEB file name.
      ansible.builtin.set_fact:
        zaproxy_deb: 'zaproxy_{{ zaproxy_version }}_all.deb'

    - name: Set fact with zaproxy status file.
      ansible.builtin.set_fact:
        zaproxy_status: '{{ updates_dir }}/zaproxy'

    - name: Include ensure_update_dir.yml task.
      ansible.builtin.include_tasks: '{{ collection_root }}/tasks/ensure_update_dir.yml'

    - name: Block for zaproxy installation status check.
      block:

        - name: Check the install status of the zaproxy package.
          ansible.builtin.shell:
            dpkg -l zaproxy | grep 'ii  zaproxy' | grep '{{ zaproxy_version }}'
          register: dpkg_l
          changed_when: false

        - name: Set fact with zaproxy installation state.
          ansible.builtin.set_fact:
            zaproxy_installed: true

      rescue:
        - name: Set fact with zaproxy installation state.
          ansible.builtin.set_fact:
            zaproxy_installed: false

#   - name: Verify zaproxy DEB checksum.
#     ansible.builtin.stat:
#       path: '{{ zaproxy_deb_dir }}{{ zaproxy_deb }}'
#       get_checksum: true
#       checksum_algorithm: sha256
#       register: stat_result
#       failed_when: stat_result.checksum == '{{ zaproxy_sha256sum }}'

    - name: Package installation block.
      when: not zaproxy_installed
      block:

        - name: Copy zaproxy DEB to host.
          ansible.builtin.copy:
            src: '{{ zaproxy_deb_dir }}{{ zaproxy_deb }}'
            dest: '/tmp//{{ zaproxy_deb }}'
            owner: root
            group: root
            mode: 0o660
          become: true

        - name: Ensure zaproxy DEB is installed.
          ansible.builtin.shell: >
            dpkg --install '/tmp/{{ zaproxy_deb }}'
          changed_when: false
          become: true

        - name: Ensure zaproxy DEB file is removed.
          ansible.builtin.file:
            path: '/tmp/{{ zaproxy_deb }}'
            state: absent
          become: true

        - name: Register package installation success.
          ansible.builtin.set_fact:
            zaproxy_installed: true

#     rescue:
#       - name: Register package installation failure.
#         ansible.builtin.set_fact:
#           install_success: false

    - name: Ensure package install status marker is up to date.
      ansible.builtin.shell: >
        echo "$(date)" > '{{ zaproxy_status }}'
      become: true
      changed_when: false
      when: zaproxy_installed

# vim: ft=ansible :
