---

- hosts: all
  gather_facts: true

  roles:
    - davedittrich.utils.kali_like
    - davedittrich.utils.branding
    - davedittrich.utils.ip_in_issue
    - davedittrich.utils.visible_bell
    - davedittrich.utils.dropins
