---

- name: Playbook for setting up a Kali-like workstation.
  hosts: all
  gather_facts: true
  vars:
    collection_root: "{{ lookup('env', 'COLLECTION_ROOT')|default(playbook_dir|dirname) }}"

  roles:
    - davedittrich.utils.kali_like
    - davedittrich.utils.kdmt
    - davedittrich.utils.branding
    - davedittrich.utils.ip_in_issue
    - davedittrich.utils.dropins

# vim: ft=ansible:
