---

# Playbook for setting up a Kali-like workstation.

- hosts: all
  gather_facts: true
  vars:
    collection_root: '{{ lookup("env", "COLLECTION_ROOT") }}'

  roles:
    - davedittrich.utils.kali_like
    - davedittrich.utils.visible_bell
    - davedittrich.utils.branding
    - davedittrich.utils.ip_in_issue
    - davedittrich.utils.dropins
