---

# Playbook to just enable natural scrolling for mouse and trackpad.

- hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  vars:
    collection_root: "{{ playbook_dir | dirname }}"
    natural_scrolling: true

  roles:
    - davedittrich.utils.kdmt
