---

# Playbook to just enable natural scrolling for mouse and trackpad.

- hosts: "{{ host | default('localhost') }}"
  gather_facts: true
  vars:
    collection_root: "{{ lookup('env', 'COLLECTION_ROOT')|default(playbook_dir|dirname) }}"
    natural_scrolling: true

  roles:
    - davedittrich.utils.kdmt
