---

- name: Playbook to swap CapsLock and Left CTRL keys.
  hosts: "{{ host | default('localhost') }}"
  gather_facts: true
  vars:
    collection_root: "{{ lookup('env', 'COLLECTION_ROOT')|default(playbook_dir|dirname) }}"
    keyboard_swapcapslockctrl: true

  roles:
    - davedittrich.utils.kdmt

# vim: ft=ansible:
