---

- name: Playbook for setting up a development workstation.
  hosts: all
  gather_facts: true
  vars:
    collection_root: "{{ lookup('env', 'COLLECTION_ROOT')|default(playbook_dir|dirname) }}"

  pre_tasks:
    - name: Set fact `keyboard_swapcapslockctrl` for `kdmt` role.
      ansible.builtin.set_fact:
        keyboard_swapcapslockctrl: '{{ hypriot_keyboard_swapcapslockctrl }}'
      when:
        - keyboard_swapcapslockctrl is not defined
        - hypriot_keyboard_swapcapslockctrl is defined

    - name: Set fact `natural_scrolling` for `kdmt` role.
      ansible.builtin.set_fact:
        natural_scrolling: '{{ hypriot_natural_scrolling }}'
      when:
        - natural_scrolling is not defined
        - hypriot_natural_scrolling is defined

    - name: Ensure required packages are present.
      ansible.builtin.apt:
        name: "{{ kali_like__packages }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      vars:
        kali_like__packages:
          - dnsutils
          - tree
          - ntp
          - vim
      become: true

  roles:
    - davedittrich.utils.branding
    - davedittrich.utils.ip_in_issue
    - davedittrich.utils.kdmt
    - davedittrich.utils.dropins

# vim: ft=ansible:
