---

# Playbook for setting up a development workstation.

- hosts: all
  gather_facts: true
  vars:
    collection_root: '{{ lookup("env", "COLLECTION_ROOT") }}'

  pre_tasks:
    - name: Ensure required packages are present.
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      vars:
        packages:
          - dnsutils
          - tree
          - ntp
          - vim
      become: true

  roles:
    - davedittrich.utils.branding
    - davedittrich.utils.ip_in_issue
    - davedittrich.utils.kdmt
    - davedittrich.utils.dropins
