---

# Playbook for setting up a development workstation.

- hosts: all
  gather_facts: true

  roles:
    - davedittrich.utils.branding
    - davedittrich.utils.ip_in_issue
    - davedittrich.utils.swapcapslockctrl
    - davedittrich.utils.visible_bell
    - davedittrich.utils.dropins
