---

# tasks file for davedittrich.utils.swapcapslockctrl

- name: Set fact with users whose accounts need to be configured
  ansible.builtin.set_fact:
    accounts: '{{ accounts | default(["root", ansible_user_id]) | unique }}'

- name: Ensure user home directories are mapped.
  include_tasks: '{{ collection_root }}/tasks/get_homedir.yml'
  loop: '{{ accounts }}'
  loop_control:
    loop_var: user

- name: Ensure required packages are present.
  ansible.builtin.package:
    name:
      - keyboard-configuration
      - console-setup
      - udev
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Stat `/etc/X11/Xsession.d` directory.
  ansible.builtin.stat:
    path: /etc/X11/Xsession.d
  register: xsessiond

- name: Ensure Xsession custom xmodmap loading dropin exists.
  ansible.builtin.copy:
    content: |
      SYSMODMAP="/etc/X11/Xmodmap"
      USERMODMAP="$HOME/.Xmodmap"
      XMODMAP="/usr/bin/xmodmap"

      if [ -x "$XMODMAP" ]; then
          for map in "$SYSMODMAP" "$USERMODMAP"; do
              if [ -f "$map" ]; then
                  logger "running $XMODMAP $map"
                  $XMODMAP "$map"
              fi
          done
      fi
    dest: /etc/X11/Xsession.d/40custom_load_xmodmap
    owner: root
    group: root
    mode: 0o644
  become: true
  when: xsessiond.stat.exists

- name: Ensure key remapping file in `/etc/udev/hwdb.d/` directory.
  ansible.builtin.copy:
    content: |
      # Match all usb keyboards
      evdev:input:b0003v*p*
      # Remap CapsLock <-> Left CTRL
      KEYBOARD_KEY_70039=leftctrl
      KEYBOARD_KEY_700E0=capslock
    dest: /etc/udev/hwdb.d/99-swapcapslockctrl.hwdb
    owner: root
    group: root
    mode: 0o644
  register: copy
  become: true

- name: Debug ``copy``.
  ansible.builtin.debug:
    msg: '{{ copy }}'
    verbosity: 2

- name: Update udevadm hwdb and trigger update.
  ansible.builtin.shell: >
    udevadm hwdb --update; udevadm trigger
  args:
    executable: /bin/bash
  when: copy.changed
  become: true

- name: Ensure Xmodmap files are customized to swap capslock/ctrl.
  include_tasks: xmodmap.yml
  vars:
    user: '{{ item }}'
  loop: '{{ accounts }}'
  when: xsessiond.stat.exists

- name: Ensure `ctrl:swapcaps` in `/etc/default/keyboard`.
  ansible.builtin.lineinfile:
    path: '/etc/default/keyboard'
    regexp: '^XKBOPTIONS=""'
    line: 'XKBOPTIONS="ctrl:swapcaps"'
    state: present
  become: true

- name: Ensure keyboard is reconfigured.
  ansible.builtin.shell: |
    dpkg-reconfigure keyboard-configuration && debconf-show keyboard-configuration
  args:
    executable: /bin/bash
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  register: result
  changed_when: false
  failed_when:
    - result.rc != 0
    - "'ctrl:swapcaps' not in result.stdout"
  become: true

# EOF
