---
# tasks file for davedittrich.utils.swapcapslockctrl

- name: Ensure required packages are present.
  ansible.builtin.package:
    name:
      - keyboard-configuration
      - console-setup
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure `ctrl:swapcaps` in `/etc/default/keyboard`.
  ansible.builtin.lineinfile:
    path: '/etc/default/keyboard'
    regexp: '^XKBOPTIONS=""'
    line: 'XKBOPTIONS="ctrl:swapcaps"'
    state: present
  become: true

- name: Ensure keyboard is reconfigured.
  ansible.builtin.shell: |
    dpkg-reconfigure keyboard-configuration && debconf-show keyboard-configuration
  args:
    executable: /bin/bash
  environment:
    DEBIAN_FRONTEND: 'noninteractive'
  register: result
  changed_when: false
  failed_when:
    - result.rc != 0
    - "'ctrl:swapcaps' not in result.stdout"
  become: true
