---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  destroy_sequence:
    - dependency
    - destroy
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
  verify_sequence:
    - verify
platforms:
  - name: debian_bullseye
    image: debian:bullseye
    dockerfile: ../shared/Dockerfile-debian_bullseye.j2
    privileged: true
    override_command: false
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: ${ANSIBLE_FORCE_COLOR:-true}
    ANSIBLE_VERBOSITY: ${ANSIBLE_VERBOSITY:-0}
    COLLECTION_ROOT: "${PWD}"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
  inventory:
    hosts:
      all:
        vars:
          accounts:
            - root
          mysql_password: '_molecule_mysql_password'
          guacamole_password: '_molecule_guacamole_password'
verifier:
  name: testinfra
  directory: ../shared/tests
  env:
    PYTHONPATH: "${PWD}/molecule/shared/tests"
    #PYTEST_ADDOPTS: "--debug -v -ra --trace-config"
    PYTEST_ADDOPTS: "${PYTEST_ADDOPTS:--v -ra}"
