---
# Ensure files to be modified exist.

- name: Prepare
  hosts: all

  tasks:
    - name: Ensure ../shared/prepare.yml tasks are applied.
      include_tasks:
        file:  ../shared/prepare.yml

    - name: Ensure Kali packages enabled.
      include_tasks:
        file:  '{{ collection_root }}/roles/kali_like/tasks/prepare_for_kali_packages.yml'

# EOF
