---
# Ensure files to be modified exist.

- name: Prepare
  hosts: all

  tasks:
    - name: Include shared `prepare` tasks.
      include_tasks: '../shared/prepare.yml'

    - name: Include Kali repo configuration tasks.
      include_tasks: '{{ collection_root }}/tasks/enable_kali_packages.yml'

# vim: ft=ansible:
