---
# Ensure files to be modified exist.

- name: Prepare
  hosts: all

  tasks:
    - name: Ensure ../shared/prepare.yml tasks are applied.
      include_tasks:
        file:  ../shared/prepare.yml

    - name: Prepare system for installing packages from Kali repos.
      include_tasks:
        file:  '{{ collection_root }}/tasks/enable_kali_packages.yml'

# EOF
