name: "davedittrich.utils.kdmt"
on:
  push:
    paths:
      - 'roles/kdmt/**'
      - 'molecule/kdmt/**'
      - '.github/workflows/kdmt.yml'
  pull_request:
    paths:
      - 'roles/kdmt/**'
      - 'molecule/kdmt/**'
      - '.github/workflows/kdmt.yml'
jobs:
  kdmt:
    runs-on: ubuntu-latest
    if: contains(github.ref, '/feature/') || contains(github.ref, '/bugfix/')
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      USER_ID: runner
      GROUP_ID: docker
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - { "distro":"ubuntu2004", "command":"/lib/systemd/systemd" }
          - { "distro":"ubuntu2204", "command":"/lib/systemd/systemd" }
          - { "distro":"debian11", "command":"/lib/systemd/systemd" }
          - { "distro":"debian12", "command":"/lib/systemd/systemd" }
        collection_role:
          - kdmt
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.10
          check-latest: true

      - run: python --version

      - name: Install dependencies
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          make install-poetry update-packages

      - name: Build the collection
        run: |
          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          echo "COLLECTION_FILE=$collection_file" >> $GITHUB_ENV

      - name: Install the collection
        run: ansible-galaxy collection install "${{ env.COLLECTION_FILE }}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test -s ${{ matrix.collection_role }}
