name: Reusable Ansible Galaxy publish workflow
on:
  workflow_call:
    inputs:
      ansible_galaxy_server:
        required: true
        type: string
        default: 'https://ansible-dev.galaxy.com'
      runs-on:
        description: Platform to execute on.
        type: string
        default: ubuntu-latest
      python-version:
        description: Python version to use.
        type: string
        default: '3.11.10'
    secrets:
      ansible_galaxy_api_key:
        required: true

jobs:
  publish:
    runs-on: ${{inputs.runs-on}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{inputs.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{inputs.python-version}}

      - name: Install dependencies
        run: |
          make install-poetry update-packages

      - name: Run the Ansible Galaxy release playbook
        env:
          ANSIBLE_GALAXY_SERVER: ${{inputs.ansible_galaxy_server}}
          ANSIBLE_GALAXY_API_KEY: ${{secrets.ansible_galaxy_api_key}}
          ANSIBLE_FORCE_COLOR: 1
        run: make publish

# EOF
