name: "release"
on:
  release:
    types:
      - created
jobs:
  #
  # Note: NOT DRY. This job matches one in release-candidate.yml.
  #
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Move project to Ansible-required location
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/davedittrich/utils
          cp -r ./ ~/.ansible/collections/ansible_collections/davedittrich/utils
      - name: Molecule test
        run: |
          molecule test
  release:
    runs-on: ubuntu-latest
    needs: molecule
    env:
      ANSIBLE_GALAXY_SERVER: 'https://galaxy.ansible.com/'
      ANSIBLE_GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
      ANSIBLE_FORCE_COLOR: 1
    #
    # Note: NOT DRY. The remainder of this workflow matches release-candidate.yml.
    #
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run the Ansible Galaxy release playbook
        run: >-
          ansible-playbook -i 'localhost,' -e '{"github_tag": "${{ github.ref }}", "publish": true}' build/galaxy_deploy.yml
