name: "release"
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint docker 'molecule[docker]' pytest testinfra yamllint

      - name: Run the Ansible Galaxy release playbook
        run: >-
          ansible-playbook -i 'localhost,' build/galaxy_deploy.yml -e "github_tag=${{ github.ref }}"
