name: "release candidate"
on:
  push:
    branches:
      - develop
#     - main
# create:
#   tags:
#     - v*
jobs:
  #
  # Note: NOT DRY. This job matches one in release.yml.
  #
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1
      PYTHON_VERSION: 3.9
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{PYTHON_VERSION}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{PYTHON_VERSION}}
          check-latest: true

      - run: python --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Move project to Ansible-required location
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/davedittrich/utils
          cp -r ./ ~/.ansible/collections/ansible_collections/davedittrich/utils

      - name: Molecule test
        run: |
          molecule test

  release_candidate:
    needs: molecule
    - name: Call publish
      uses: davedittrich/utils/.github/workflows/publish.yml@develop
      with:
        runs-on: ubuntu-latest
        python-version: ${{PYTHON_VERSION}}
        ansible_galaxy_server: https://galaxy-dev.ansible.com/
      secrets:
        ansible_galaxy_api_key: ${{secrets.GALAXYDEV_API_KEY}}

# EOF
