name: "release"
on:
  push:
    branches:
      - develop
      - main
  create:
    tags:
      - v*
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Determine Python versions available.
        run: |
          echo "Available Python versions"
          echo "----"
          cd /opt/hostedtoolcache/Python && ls
          echo "----"

      - name: Set up Python 3.11.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.10"
          check-latest: true

      - run: python --version

      - name: Dump select GitHub event context
        env:
          GITHUB_EVENT: ${{ toJson(github.event) || 'None' }}
          RUNNER: ${{ toJson(runner) }}
        run: |
          printf 'github.event=%s\n' "$GITHUB_EVENT"
          echo "github.ref=${{ github.ref }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.ref_protected=${{ github.ref_protected }}"
          echo "github.ref_type=${{ github.ref_type }}"
          printf 'runner=%s\n' "$RUNNER"
          echo 'See: https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-github-context'

      - name: Install dependencies
        env:
          DEB_PYTHON_INSTALL_LAYOUT: deb_system pip install .
        run: |
          python3 -m pip install --upgrade pip
          make install-poetry update-packages

      - name: Move project to Ansible-required location
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/davedittrich/utils
          cp -r ./ ~/.ansible/collections/ansible_collections/davedittrich/utils

      - name: Molecule test
        run: |
          molecule test

  release_candidate:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref_name, '-')
    needs: molecule
    uses: davedittrich/utils/.github/workflows/publish.yml@develop
    with:
      runs-on: ubuntu-latest
      python-version: "3.11.10"
      ansible_galaxy_server: https://galaxy-dev.ansible.com/
    secrets:
      ansible_galaxy_api_key: ${{secrets.GALAXYDEV_API_KEY}}

  release:
    if: startsWith(github.ref, 'refs/tags/v') && ! contains(github.ref_name, '-')
    needs: molecule
    uses: davedittrich/utils/.github/workflows/publish.yml@develop
    with:
      runs-on: ubuntu-latest
      python-version: "3.11.10"
      ansible_galaxy_server: https://galaxy.ansible.com/
    secrets:
      ansible_galaxy_api_key: ${{secrets.GALAXY_API_KEY}}

# EOF
