name:  release candidate
on:
  push:
    branches:
      - develop
  release_candidate:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'rc')
    needs: molecule
    env:
      ANSIBLE_GALAXY_SERVER: 'https://galaxy-dev.ansible.com/'
      ANSIBLE_GALAXY_API_KEY: ${{ secrets.GALAXYDEV_API_KEY }}
      ANSIBLE_FORCE_COLOR: 1
    #
    # Note: NOT DRY. The remainder of this workflow matches release.yml.
    #
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible ansible-lint docker 'molecule[docker]' pytest pytest-testinfra yamllint

      - name: Run the Ansible Galaxy release playbook
        run: >-
          ansible-playbook -i 'localhost,' build/galaxy_deploy.yml -e "github_tag=${{ github.ref }}"
