name: "release"
on:
  push:
    branches:
      - develop
#     - main
  create:
    tags:
      - v*
jobs:
  #
  # Note: NOT DRY. This job matches one in release.yml.
  #
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - name: Dump context
        uses: davedittrich/utils/.github/workflows/context.yml@develop

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          check-latest: true

      - run: python --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Move project to Ansible-required location
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/davedittrich/utils
          cp -r ./ ~/.ansible/collections/ansible_collections/davedittrich/utils

      - name: Molecule test
        run: |
          molecule test

  release_candidate:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref_name, '-')
    needs: molecule
    uses: davedittrich/utils/.github/workflows/publish.yml@develop
    with:
      runs-on: ubuntu-latest
      python-version: 3.9
      ansible_galaxy_server: https://galaxy-dev.ansible.com/
    secrets:
      ansible_galaxy_api_key: ${{secrets.GALAXYDEV_API_KEY}}

  release:
    if: startsWith(github.ref, 'refs/tags/v') && ! contains(github.ref_name, '-')
    needs: molecule
    uses: davedittrich/utils/.github/workflows/publish.yml@develop
    with:
      runs-on: ubuntu-latest
      python-version: 3.9
      ansible_galaxy_server: https://galaxy.ansible.com/
    secrets:
      ansible_galaxy_api_key: ${{secrets.GALAXY_API_KEY}}

# EOF
